# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  # push:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: windows-latest # self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      # https://github.com/actions/runner/issues/686#issuecomment-1636899369
      - name: Allow powershell
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"

      - name: Check powershell version
        run: $host.Version

      - name: Prepare build
        shell: powershell
        run: |
          mkdir BuildJob

      - name: Cloning repositories
        shell: powershell
        working-directory: ./BuildJob
        run: |
          ..\clone-repos.ps1

      - name: Building
        shell: powershell
        working-directory: ./BuildJob
        run: |
          ..\build.ps1

      - name: Cleaning up the projects
        shell: powershell
        working-directory: ./BuildJob
        run: |
          ..\cleanup-projects.ps1

      - name: Get-Location
        shell: powershell
        run: Get-Location

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './BuildJob/Published/wwwroot'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
